<div class="container">
    <div class="row">
        <div class="col-xs-12">

            <h3>Детали вопроса - <?=$this->question->title ?></h3>
            <h5>Автор: <?=$this->author->username ?></h5>
            <p>
                <?=$this->question->description ?>
            </p>
            <br/>
            <hr/>
            <h5>Ответы:</h5>

            <?php if(count($this->answers) > 0  ):?>
                <?php foreach($this->answers as $a):?>
                    <p><?=$a->answer ?></p>
                <?php endforeach; ?>
            <?php else:?>
            <p> Нет ответов</p>
            <?php endif;?>

            <?php if(!empty($this->identity)):?>
                <hr/>
                <h5>Ответить</h5>
                <div>
                    <?=$this->form; ?>
                </div>
            <?php endif;?>
        </div>
    </div>


</div>